services:
  mysuperduperpetproject:
    image: ${DOCKER_REGISTRY-}mysuperduperpetproject
    container_name: 'transfer_api'
    build:
      context: .
      dockerfile: MySuperDuperPetProject/Dockerfile
    ports:
      - "5005:3000"
    depends_on: 
      - postgres
      

  postgres:
    image: postgres:13.3
    container_name: 'DB_PostgreSQL'
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "transfer_db"
      POSTGRES_USER: "adm"
      POSTGRES_PASSWORD: "adm"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adm -d transfer_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
