// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySuperDuperPetProject.TransferDatabaseContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MySuperDuperPetProject.Migrations
{
    [DbContext(typeof(TransferDbContext))]
    [Migration("20241201090941_my_first_migration")]
    partial class my_first_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MySuperDuperPetProject.TransferDatabaseContext.Transfers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PageFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PageTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TransferUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("hub_transfers", "transfers");
                });

            modelBuilder.Entity("MySuperDuperPetProject.TransferDatabaseContext.TransfersStatistic", b =>
                {
                    b.Property<string>("HashId")
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HashId");

                    b.ToTable("hub_transfers_statistic", "transfers");
                });

            modelBuilder.Entity("MySuperDuperPetProject.TransferDatabaseContext.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("hub_users", "users");
                });

            modelBuilder.Entity("MySuperDuperPetProject.TransferDatabaseContext.Transfers", b =>
                {
                    b.HasOne("MySuperDuperPetProject.TransferDatabaseContext.User", "User")
                        .WithMany("Transfers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MySuperDuperPetProject.TransferDatabaseContext.User", b =>
                {
                    b.Navigation("Transfers");
                });
#pragma warning restore 612, 618
        }
    }
}
